before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mysql
  - mongodb
script:
  - cd dummy
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec cucumber
